# Generated by Django 6.0.7 on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expencess', '0002_settlementpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementpayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank transfer')], default='bank', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settlementpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved')], default='approved', max_length=10),
        ),
    ]
