# Generated by Django 6.0.7 on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expencess', '0003_settlementpayment_payment_method_and_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlementpayment',
            name='status',
            field=models.CharField(
                choices=[('pending', 'Pending approval'), ('approved', 'Approved')],
                default='pending',
                max_length=10,
            ),
        ),
    ]
